.PHONY: build p1 p2 p3

BIN=./bin
PROCESS=process

build:
	go build -o $(BIN)/$(PROCESS) main.go

THREE_SIMULATOR=10004 10003 10002

p1:
	$(BIN)/$(PROCESS) 1 $(THREE_SIMULATOR)

p2:
	$(BIN)/$(PROCESS) 2 $(THREE_SIMULATOR)

p3:
	$(BIN)/$(PROCESS) 3 $(THREE_SIMULATOR)
